### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by O4dg** [AKASH-UWU/Zota-Proxy-Scrapper#1]
I have a question why are proxies saved like this? Isn't it better in a text document, proxy ip only, for example 129.88.88.8:80 only for ease of use?

**Comment by AKASH-UWU** [comment]
Thank you for your suggestion. I have now included support for the `ip:port` format in the `working_proxies.txt` file for easier access. Please let me know if you have any further issues or questions regarding this project. Otherwise, I will proceed to close this issue.
